image: gitpod/workspace-full:latest

ports:
- port: 8080
  onOpen: open-browser
  
tasks:
- init: ./gradlew clean build
  command: java -jar build/libs/*.jar

vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.0:9xQZtwTUg4bdXHCMyxM7vQ==